MONGO_PORT = 27017
MONGO_DATABASE = "toonalysis"
MONGO_COLLECTION = "toons"

SCRAPER_URL = "https://toonhq.org/groups"
SCRAPER_REGEX_PATTERN = r'window.STATE = (\{[^;]+\});'
SCRAPER_SYNCED_DEFAULT_ORGANIC = "None"
SCRAPER_UNSYNCED_DEFAULT_ORGANIC = "?"
